name: L3 API Pull request action

on:
  pull_request:
    paths:
      - "**.js"

env:
  CI: true
  MONGODB_URL: mongodb://localhost:27017/test

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Node dependency install
        run: yarn install

      - name: Run test
        run: npx jest
